# Generated by Django 3.2.9 on 2022-12-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=50)),
                ('taskdesc', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('dateadded', models.DateTimeField()),
            ],
        ),
    ]
