# Generated by Django 3.2.9 on 2022-12-18 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateadded',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 1, 41, 20, 765240)),
        ),
    ]
