# Generated by Django 3.2.9 on 2022-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateadded',
            field=models.DateTimeField(),
        ),
    ]
