# Generated by Django 3.2.9 on 2022-12-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_task_taskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(default=1),
        ),
    ]
