# Generated by Django 3.2.9 on 2022-12-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskId',
        ),
    ]
