# Generated by Django 3.2.9 on 2022-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_remove_task_taskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskId',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
