# Generated by Django 3.2.9 on 2022-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_alter_task_taskid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='taskId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
